apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
  namespace: kube-ops
  labels:
    pv: sonar-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /gpfs/vmfs/nfs/k8s/ops-data/sonarqube/
    server: 172.16.52.200
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      pv: sonar-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G
